#!/bin/sh
#
# Ansible Vault Secrets Git Hook
#
# Hook to check if an un-encrypted FILE_PATTERN file is being commited. Useful if secrets 
# are retained in ansible vault encrypted file(s) that should never be committed to the repository
# un-encrypted. Contact a repository owner for the ansible vault password.
#

# set -o xtrace
set -o nounset

FILE_PATTERN="ansible/vaults/[A-Za-z0-9]+\.yml"
ENCRYPTED_PATTERN="\$ANSIBLE_VAULT"

is_encrypted() {
  local file=$1
  if ! git show :"$file" | grep -q "^${ENCRYPTED_PATTERN}"; then
    echo -e "Located a staged file that should be encrypted:\n> ${file}\n"
    echo -e "Please un-stage this file. If you are adding or updating this file, please encrypt it before staging."
    echo -e "Alternatively, you can git checkout the latest encrypted version of the file before committing.\n"
    echo -e "Remember... Only YOU Can Prevent Secret Leakage."
    exit 1
  fi
}

echo "Running pre-commit checks..."
git diff --cached --name-only | grep -E "${FILE_PATTERN}" | while IFS= read -r line; do
  is_encrypted "${line}"
done