- name: Check if server is proxmox server
  shell: pveversion --verbose | grep proxmox-ve | wc -l
  register: is_proxmox

- block:
    - name: Update apt repo and do a full-upgrade on servers
      apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: full
      register: updatesys

    - name: Display the last line of the previous task to check the stats
      debug:
        msg: "{{ updatesys.stdout_lines | last }}"

    - name: Clean up after apt
      apt:
        autoremove: true
        autoclean: true
  become: "{{ is_proxmox.stdout == '0' }}"

- name: Update certs on proxmox servers
  command: pvecm updatecerts
  when: is_proxmox.stdout == "1"
