- name: Update apt repo and do a full-upgrade on servers
  register: updatesys
  apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist 

- name: Display the last line of the previous task to check the stats
  debug:
    msg:  "{{updatesys.stdout_lines|last}}"

- name: Remove dependencies that are no longer required
  apt:
    autoremove: true

- name: Remove useless packages from the cache
  apt:
    autoclean: true

- name: check if server is proxmox server
  shell: pveversion --verbose | grep proxmox-ve | wc -l
  register: is_proxmox

- name: update certs on proxmox servers
  shell: pvecm updatecerts
  when: is_proxmox.stdout == "1"