---
plugin: nmap
address: 192.168.16.0/24
strict: false
ipv4: yes
ports: yes
sudo: true
groups:
  without_hostname: "'192.168.16' in name"
  with_ssh: "ports | selectattr('service', 'equalto', 'ssh')"