- name: Create mafen account
  hosts: "{{ ansible_override_hosts | default('mafens-playground') }}"
  become: yes
  gather_facts: no
  vars:
    user_name: mafen
    user_comment: "Mafen"
  roles:
    - create-user
