---
# ansible-playbook -i inventory setup-tailscale.yml
# https://galaxy.ansible.com/artis3n/tailscale
- name: fix bitbucket known hosts entry
  hosts: all
  tasks:
    - name: check for known hosts file 
      stat:
        path: "~/.ssh/known_hosts"
      register: known_hosts

    - name: fix bitbucket known hosts entry
      shell: "ssh-keygen -R bitbucket.org && curl https://bitbucket.org/site/ssh >> ~/.ssh/known_hosts"
      when: known_hosts.stat.exists
