- name: set hostnames
  hosts: "{{ ansible_override_hosts | default('all') }}"
  gather_facts: no
  become: yes
  vars_files: "../ansible-sites/{{ lookup('env', 'SITE') }}/vault.yml"
  tasks:
    - name: set system hostname
      command: hostnamectl set-hostname {{ inventory_hostname | split('.') | first }}

      # example
      # [consul_servers]
      # consul-1 ansible_ssh_host=192.168.31.105

