---
- name: install docker and docker compose
  hosts: "{{ ansible_override_hosts | default('docker_hosts') }}" 
  become: true
  vars_files: "../ansible-sites/{{ lookup('env', 'SITE') }}/vault.yml"
  vars:
    docker_edition: 'ce'
    docker_package_state: present
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted
    docker_install_compose_plugin: true
    docker_compose_package: docker-compose-plugin
    docker_compose_package_state: present
    docker_users:
    - "{{ ansible_env.SUDO_USER }}"
  roles:
    - geerlingguy.docker
  tasks:
    - name: add a vm.overcommit_memory setting at the end of the sysctl.conf
      sysctl: name=vm.overcommit_memory value=1 state=present reload=yes

    - name: Create docker-prune cron job
      ansible.builtin.copy:
        dest: /etc/cron.weekly/docker-prune
        content: |
          #!/bin/bash
          /usr/bin/docker system prune -f
        mode: '0755'
    
    - name: Configure logrotate for Docker containers
      ansible.builtin.copy:
        dest: /etc/logrotate.d/docker-container
        content: |
          /var/lib/docker/containers/*/*.log {
            rotate 15
            daily
            compress
            missingok
            delaycompress
            copytruncate
          }
        mode: '0644'

    - name: Create disable-hugepages.service file
      lineinfile:
        path: /etc/systemd/system/disable-hugepages.service
        line: |
          [Unit]
          Description="Disable Transparent Hugepage"
          Before=docker.service
          [Service]
          Type=oneshot
          ExecStart=/bin/bash -c 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'
          ExecStart=/bin/bash -c 'echo never > /sys/kernel/mm/transparent_hugepage/defrag'
          [Install]
          RequiredBy=docker.service
        create: yes
        mode: '0644'

    - name: Enable and start disable-hugepages.service
      systemd:
        name: disable-hugepages
        enabled: true
        state: started

    - name: Reload systemd
      systemd:
        daemon_reload: true

    - name: Set kernel.printk
      command: echo "3 4 1 3" | tee /proc/sys/kernel/printk

    - name: Configure kernel.printk in sysctl.conf
      ansible.builtin.replace:
        path: /etc/sysctl.conf
        regexp: '^kernel.printk.*$'
        replace: 'kernel.printk = 3 4 1 3'

    - name: Set vm.overcommit_memory
      sysctl:
        name: vm.overcommit_memory
        value: 1
        sysctl_file: /etc/sysctl.conf

    - name: Set net.core.somaxconn
      sysctl:
        name: net.core.somaxconn
        value: 1024
        sysctl_file: /etc/sysctl.conf

    - name: Set vm.max_map_count
      sysctl:
        name: vm.max_map_count
        value: 262144
        sysctl_file: /etc/sysctl.conf

    - name: Set vm.swappiness
      sysctl:
        name: vm.swappiness
        value: 1
        sysctl_file: /etc/sysctl.conf