---
- name: Setup Tailscale
- hosts: "{{ ansible_override_hosts | default('tailscale_hosts') }}"
  #vars_files: "../ansible-sites/{{ lookup('env', 'SITE') }}/vault.yml"
  roles:
    # https://galaxy.ansible.com/artis3n/tailscale
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
        tailscale_args: "--advertise-routes={{ tailscale_routes }} --hostname={{ tailscale_hostname | default('tailscale-vm') }}"
  tasks:
    - name: Set net.ipv4.ip_forward
      become: yes
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes
        sysctl_set: true

    - name: Set ipv6.conf.all.forwarding
      become: yes
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.forwarding
        value: '1'
        state: present
        reload: yes
        sysctl_set: true
