- name: setup influx to {{ log_server }}
  hosts: "{{ ansible_override_hosts | default('docker_hosts') }}" 
  gather_facts: no
  vars_files: "../ansible-sites/{{ lookup('env', 'SITE') }}/vault.yml"
  tasks:
    - name: create /apps directory
      become: yes
      file:
        path: /apps
        state: directory        
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0775
        recurse: yes

    - name: Clone influx repository
      git:
        repo: git@bitbucket.org:rammounts/influx.git
        dest: /apps/influx
        update: no
        accept_hostkey: yes

    - name: check if influx is running
      shell: docker ps --format='table {{'{{'}}.Names{{'}}'}}\t{{'{{'}}.State{{'}}'}}' | grep influx | grep running | wc -l
      register: service_count

    - name: start influx
      shell: make start
      args:
        chdir: /apps/influx
      when: service_count.stdout == "0"

    - name: restart influx
      shell: make restart
      args:
        chdir: /apps/influx
      when: service_count.stdout == "1" and service_conf.changed

