- name: Stop seattle services
  hosts: seattle_backup_servers
  gather_facts: false
  roles:
    # - role: update-system
    #   become: yes

    - role: servicectl
      vars: 
        service_name: conx
        service_environment: production
        service_action: stop
    - role: servicectl
      vars: 
        service_name: conx
        service_environment: staging
        service_action: stop

    - role: servicectl
      vars: 
        service_name: payment
        service_environment: production
        service_action: stop
    - role: servicectl
      vars: 
        service_name: payment
        service_environment: staging
        service_action: stop

    - role: servicectl
      vars: 
        service_name: rma
        service_environment: production
        service_action: stop
    - role: servicectl
      vars: 
        service_name: rma
        service_environment: staging
        service_action: stop

    - role: servicectl
      vars: 
        service_name: shopify
        service_environment: production
        service_action: stop
    - role: servicectl
      vars: 
        service_name: shopify
        service_environment: staging
        service_action: stop

    - role: servicectl
      vars: 
        service_name: shopify-data-upload
        service_environment: production
        service_action: stop
    - role: servicectl
      vars: 
        service_name: shopify-data-upload
        service_environment: staging
        service_action: stop

    