- name: sync seattle backups
  hosts: seattle_backup_servers
  gather_facts: no
  vars_files: "../ansible-sites/{{ lookup('env', 'SITE') }}/vault.yml"
  tasks:
    - name: install dependencies
      become: yes
      apt:
        update_cache: yes
        name:
          - rsync
          - dnsutils
        state: present
    
    - name: create /apps directory
      become: yes
      file:
        path: /apps
        state: directory        
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0775

    - known_hosts:
        name: "{{ item }}"
        key: "{{ lookup('pipe', 'ssh-keyscan {{ item }},`dig +short {{ item }}`') }}"
        state: present
      with_items:
      - harbor-seattle.rammount.com
      - bitbucket.org

    - name: rsync from harbor-seattle.rammount.com
      shell: rsync -chazP --stats --exclude '.erlang.cookie' anvil@harbor-seattle.rammount.com:/apps/ /apps
    