---
# https://jianjye.medium.com/how-to-update-user-password-with-ansible-f971f41a3b3e
# ansible-playbook -i inventory update-vagrant-password.yml --extra-vars newpassword=12345678
- hosts: "{{ ansible_override_hosts | default('vagrant_hosts') }}"
  become: yes
  vars_files: "../ansible-sites/{{ lookup('env', 'SITE') }}/vault.yml"
  tasks:
    - name: Change user password
      user:
        name: vagrant
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"