- name: Create docker-prune cron job
  become: true
  ansible.builtin.copy:
    dest: /etc/cron.weekly/docker-prune
    content: |
      #!/bin/bash
      /usr/bin/docker system prune -f
    mode: '0755'

- name: Configure logrotate for Docker containers
  become: true
  ansible.builtin.copy:
    dest: /etc/logrotate.d/docker-container
    content: |
      /var/lib/docker/containers/*/*.log {
        rotate 15
        daily
        compress
        missingok
        delaycompress
        copytruncate
      }
    mode: '0644'

- name: Create disable-hugepages.service file
  become: true
  lineinfile:
    path: /etc/systemd/system/disable-hugepages.service
    line: |
      [Unit]
      Description="Disable Transparent Hugepage"
      Before=docker.service
      [Service]
      Type=oneshot
      ExecStart=/bin/bash -c 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'
      ExecStart=/bin/bash -c 'echo never > /sys/kernel/mm/transparent_hugepage/defrag'
      [Install]
      RequiredBy=docker.service
    create: yes
    mode: '0644'

- name: Enable and start disable-hugepages.service
  become: true
  systemd:
    name: disable-hugepages
    enabled: true
    state: started

# https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc
- name: Set fs.inotify.max_user_watches
  become: true
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: '524288'
    sysctl_file: /etc/sysctl.conf

- name: Set vm.overcommit_memory
  become: true
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: '1'
    sysctl_file: /etc/sysctl.conf

- name: Set net.core.somaxconn
  become: true
  ansible.posix.sysctl:
    name: net.core.somaxconn
    value: '1024'
    sysctl_file: /etc/sysctl.conf

- name: Set vm.max_map_count
  become: true
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '262144'
    sysctl_file: /etc/sysctl.conf

- name: Set vm.swappiness
  become: true
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '1'
    sysctl_file: /etc/sysctl.conf

- name: Create /apps directory
  become: true
  file:
    path: /apps
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775
    recurse: true

- name: Reload systemd
  become: true
  systemd:
    daemon_reload: true
