- name: Check if restart is required
  hosts: "{{ ansible_override_hosts | default('all') }}"
  become: yes
  gather_facts: no
  tasks:
    - name: Check that the reboot-requied exists
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot {{ inventory_hostname }} and wait for its return
      ansible.builtin.reboot:
        reboot_timeout: 3600
      when: reboot_required.stat.exists
            