---
- name: disable esm login nag message
  hosts: proxmox_template
  become: true
  tasks:
  - name: Creates directory /etc/apt/apt.conf.d/off
    file:
      path: /etc/apt/apt.conf.d/off
      state: absent


  - name: Ansible remove esm files
    file:
      path: "{{ item }}"
      state: absent
    with_items: 
    - /etc/apt/apt.conf.d/20apt-esm-hook.conf
    - /etc/update-motd.d/88-esm-announce
    - /var/lib/ubuntu-advantage/messages/motd-esm-announce
