---
- name: ensure app/deploy public key is present on git server
  hosts: proxmox_template
  tasks:
    # - name: ensure private key is present
    #   copy: 
    #     src: /home/{{ lookup('env', 'USER') }}/.ssh/id_ed25519
    #     dest: /home/{{ ansible_user }}/.ssh/id_ed25519
    #     mode: 0600

    - copy:
        src: ./keys/npi-pub.keys.txt
        dest: /home/vagrant/.ssh/authorized_keys