---
- name: ensure id_ed25519 key is present on hosts
  hosts: "{{ ansible_override_hosts | default('all') }}"
  become: no
  gather_facts: no
  vars:
    - ssh_public_keys_file: "./keys/{{ lookup('env', 'SITE') }}-pub.keys.txt"
  tasks:
    - name: Set up multiple authorized keys
      authorized_key:
        user: '{{ ansible_user }}'
        state: present
        key: '{{ item }}'
      with_items: '{{ lookup("file", ssh_public_keys_file).splitlines() }}'

    - set_fact: ssh_key_filename="id_ed25519"
      when: ssh_key_filename is undefined

    - debug:
        msg: "ssh_key_filename: {{ ssh_key_filename }}"

    - name: ensure id_ed25519 private key is present
      copy: 
        src:  ~/.ssh/{{ ssh_key_filename }}
        dest: ~/.ssh/id_ed25519_{{ lookup('env', 'SITE') }}
        mode: 0600
        force: no
    
    - name: ensure id_ed25519 public key is present
      copy: 
        src:  ~/.ssh/{{ ssh_key_filename }}.pub
        dest: ~/.ssh/id_ed25519_{{ lookup('env', 'SITE') }}.pub
        mode: 0644
        force: no

    - name: create link to id_ed25519 private key
      file:
        src:    ~/.ssh/id_ed25519_{{ lookup('env', 'SITE') }}
        dest:   ~/.ssh/id_ed25519
        state:  link
        mode:   0600

    - name: create link to id_ed25519 public key
      file:
        src:    ~/.ssh/id_ed25519_{{ lookup('env', 'SITE') }}.pub
        dest:   ~/.ssh/id_ed25519.pub
        state:  link
        mode:   0644

    - name: check if server is proxmox server
      shell: pveversion --verbose | grep proxmox-ve | wc -l
      register: is_proxmox

    - name: update certs on proxmox servers
      shell: pvecm updatecerts
      when: is_proxmox.stdout == "1"

    