---
- name: dotfiles module 
  hosts: all
  become: no
  gather_facts: no
  tasks:
  - name: ensure github.com is a known host
    lineinfile:
      dest: /root/.ssh/known_hosts
      create: yes
      state: present
      line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
      regexp: "^github\\.com"
  - name: clone dotfiles repository
    git:
       repo: git@github.com:ilude/dotfiles.git
       dest: ~/.dotfiles
       clone: yes
       update: yes
  - name: install dotfiles
    command: ~/.dotfiles/install