---
- hosts: proxmox_template
  become: true
  vars:
    docker_edition: 'ce'
    docker_package_state: present
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted
    docker_install_compose_plugin: true
    docker_compose_package: docker-compose-plugin
    docker_compose_package_state: present
    docker_users:
    - "{{ ansible_env.SUDO_USER }}"
  roles:
    - geerlingguy.docker
  tasks:
    - name: add a vm.overcommit_memory setting at the end of the sysctl.conf
      sysctl: name=vm.overcommit_memory value=1 state=present reload=yes