---
- name: setup sudoer.d file
  hosts: proxmox_quorum_hosts
  become: true
  tasks:
  - name: Set includedir in sudoers
    lineinfile:
      dest: /etc/sudoers
      line: "@includedir /etc/sudoers.d"
      state: present
      validate: "/usr/sbin/visudo -cf %s"

  - name: Add user {{ ansible_user }} to sudo
    lineinfile:
      path: /etc/sudoers.d/{{ ansible_user }}
      line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
      state: present
      mode: 0440
      create: yes
      validate: 'visudo -cf %s'


