---
# ansible-playbook -i inventory update-vagrant-password.yml --extra-vars newpassword=12345678
- hosts: npi_docker_hosts
  become: yes
  tasks:
    - name: Change user password
      user:
        name: vagrant
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"