---
- name: Ansible apt module 
  hosts: "{{ ansible_override_hosts | default('all') }}"
  become: yes
  pre_tasks:
    - name: include env vars
      include_vars: "vaults/{{ lookup('env', 'SITE') }}.yml"
      tags: ["always"]
  tasks:
  - name: Creating /etc/apt/apt.conf.d/99-Phased-Updates
    copy:
      dest: "/etc/apt/apt.conf.d/99-Phased-Updates"
      content: |
        Update-Manager::Always-Include-Phased-Updates "1";
        APT::Get::Always-Include-Phased-Updates "1";

  - name: Update apt repo and cache on all Debian/Ubuntu boxes
    apt: 
      update_cache: yes
      cache_valid_time: 3600
  
  - name: Full-Upgrade on servers
    apt: 
      upgrade: dist 

  - name: Upgrade all Packages
    register: updatesys
    apt:
      name: "*"
      state: latest

  - name: Display the last line of the previous task to check the stats
    debug:
      msg:  "{{updatesys.stdout_lines|last}}"

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
